language: node_js

node_js:
  - '9'

before_deploy:
  - npm run clean && npm run build

deploy:
  - provider: npm
    email: 'devmonk@mediamonks.com'
    api_key: $NPM_TOKEN
    on:
      tags: true
      all_branches: true
      node: '9'
    skip_cleanup: true
